apiVersion: apps/v1
kind: Deployment
metadata:
    name: nest-deployment
    labels:
        app: nest
spec:
    replicas: 2 # Create two pods
    selector:
        matchLabels:
            app: nest
    template:
        metadata:
            labels:
                app: nest
        spec:
            containers:
                - name: nest
                  image: 284845684968.dkr.ecr.us-east-1.amazonaws.com/test-api:worker-main-latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: INI_ENV
                        value: "test"
                  resources:
                      limits:
                          cpu: "500m"
                          memory: "512Mi"
                      requests:
                          cpu: "200m"
                          memory: "256Mi"
