apiVersion: v1
kind: Service
metadata:
    name: nest-service
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb # Using Network Load Balancer
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
    selector:
        app: nest
    ports:
        - port: 80
          targetPort: 3000
          protocol: TCP
    type: LoadBalancer
status:
    loadBalancer:
        ingress:
            - ip: 192.0.2.127
