# Do Something here
# This is a placeholder for the main workflow file.
name: Deploy Terraform to AWS
on:
    push:
        branches:
            - "main"

permissions:
    id-token: write
    contents: read
jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build and Push Docker Image
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: test-api
                  WORKER_IMAGE_TAG: worker-${{ github.ref_name }}-latest
              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$WORKER_IMAGE_TAG
    deploy:
        needs: build
        name: Example Deploy Terraform to AWS
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                  aws-region: us-east-1

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              run: |
                  terraform init

            - name: Terraform Apply
              run: |
                  terraform apply -auto-approve

            - name: End Deploy
              run: echo "Deploy Success"
